name: Manually Deploy PR to Firebase

on:
  workflow_dispatch:
    inputs:
      prNumber:
        description: 'Number of the PR to deploy'
        required: true

jobs:
  deploy-fork-pr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v2
      with:
        node-version: 16
        check-latest: true

    - name: Checkout PR
      run: |
        gh pr checkout ${{ github.event.inputs.prNumber }}
        echo "GITHUB_HEAD_REF=pr-${{ github.event.inputs.prNumber }}" >> $GITHUB_ENV

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.84.0'
        extended: true

    - name: Install node Modules
      run: npm install

    - name: Setup GCP Auth
      uses: google-github-actions/setup-gcloud@v0.2.1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Disable Crawling on staging site
      run: |
        printf "User-agent: *\nDissallow: /\n" > layouts/robots.txt

    - name: Build
      run: hugo

    - name: Deploy
      id: deploy
      uses: actions/github-script@v4
      with:
        script: |
            const deploy = require('./deploy.js')
            await deploy({ expires: '72h' })
    - name: Comment with Staging Link
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        number: ${{ github.event.inputs.prNumber }}
        message: |
          PR deployed to: ${{ steps.deploy.outputs.staging_url }}
          Expires at: ${{ steps.deploy.outputs.expiration }}
