name: Deploy Stage to Firebase

on:
  push:
    branches:
    - develop
  workflow_dispatch: {}

jobs:
  deploy-stage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v2
      with:
        node-version: 16
        check-latest: true
    - uses: actions/checkout@v2.3.4
      with:
        submodules: false

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.84.0'
        extended: true

    - name: Disable Crawling on staging site
      run: |
        printf "User-agent: *\nDissallow: /\n" > layouts/robots.txt

    - name: Build
      run: |
        npm --version
        npm install && hugo

    - name: Deploy
      uses: w9jds/firebase-action@master
      with:
        args: deploy --message \"${{ github.event.head_commit.commit_sha }}\"
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
