name: Update Hugo Modules

on:
  schedule:
  - cron: '*/15 * * * *'
  workflow_dispatch: {}

jobs:
  deploy:
    name: Update Hugo Modules
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}

    - name: Checkout Branch
      uses: paketo-buildpacks/github-config/actions/pull-request/checkout-branch@main
      with:
        branch: automation/hugo-modules/update

    - name: Install Hugo
      run: |
        mkdir -p .bin
        curl "https://github.com/gohugoio/hugo/releases/download/v0.82.0/hugo_extended_0.82.0_Linux-64bit.tar.gz"\
          --silent \
          --location \
          --output /tmp/hugo.tar.gz
        tar -xOzvf /tmp/hugo.tar.gz 'hugo' > .bin/hugo
        chmod +x .bin/hugo
        rm /tmp/hugo.tar.gz

    - name: Update Modules
      run: |
        .bin/hugo mod get -u ./...
        .bin/hugo mod tidy
        rm -rf .bin/

    - name: Commit
      id: commit
      uses: paketo-buildpacks/github-config/actions/pull-request/create-commit@main
      with:
        message: "Updating Hugo modules"
        pathspec: "."
        keyid: ${{ secrets.PAKETO_BOT_GPG_SIGNING_KEY_ID }}
        key: ${{ secrets.PAKETO_BOT_GPG_SIGNING_KEY }}

    - name: Push Branch
      if: ${{ steps.commit.outputs.commit_sha != '' }}
      uses: paketo-buildpacks/github-config/actions/pull-request/push-branch@main
      with:
        branch: automation/hugo-modules/update

    - name: Open Pull Request
      if: ${{ steps.commit.outputs.commit_sha != '' }}
      uses: paketo-buildpacks/github-config/actions/pull-request/open@main
      with:
        token: ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}
        title: "Updates Hugo modules"
        branch: automation/hugo-modules/update
